app = "howgamersgame"
primary_region = "lax"

[build]

[[services]]
internal_port = 3000
protocol = "tcp"

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
